### ISSUE TITLE
ERROR [SymbolService] Error: No data provider has been found.

### ISSUE THREAD

**Issue by DerAndereJohannes** [ghostfolio/ghostfolio#1016]
Hi! This project looks super awesome and I appreciate it a lot! I have managed to set everything up using the docker-compose image without any hitch. The live demo works flawlessly on my setup, however I am having trouble with adding new activities to my account. 

Here is the error code from the ghostfolio instance whenever I try to type anything into the Symbol/ISIN field:
```sh
[Nest] 1  - 06/15/2022, 11:57:49 AM   ERROR [SymbolService] Error: No data provider has been found.
[Nest] 1  - 06/15/2022, 11:57:49 AM   ERROR [ExceptionsHandler] No data provider has been found.
Error: No data provider has been found.
    at DataProviderService.getDataProvider (/ghostfolio/apps/api/main.js:1:197667)
    at DataProviderService.<anonymous> (/ghostfolio/apps/api/main.js:1:197229)
    at Generator.next (<anonymous>)
    at /ghostfolio/apps/api/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/ghostfolio/apps/api/node_modules/tslib/tslib.js:113:16)
    at DataProviderService.search (/ghostfolio/apps/api/main.js:1:197070)
    at SymbolService.<anonymous> (/ghostfolio/apps/api/main.js:1:218782)
    at Generator.next (<anonymous>)
    at /ghostfolio/apps/api/node_modules/tslib/tslib.js:117:75
```

Here is my setup:
- Synology NAS
- Docker version 20.10.3, build b35e731
- docker-compose version 1.28.5, build 1bbbad71

Thanks in advance!

**Comment by dtslvr** [comment]
Thank you the bug report @DerAndereJohannes.

I was able to reproduce the issue and find a fix.

**Comment by DerAndereJohannes** [comment]
Awesome thanks! It is now working correctly! :-)
