### ISSUE TITLE
"Oops! Something went wrong" error when opening holdings

### ISSUE THREAD

**Issue by MisterDeee** [ghostfolio/ghostfolio#1213]
Added some activity for a single stock. Went to look at Holdings, received above error. Looked into logs:

[Nest] 845  - 09/01/2022, 9:48:20 AM    WARN [PortfolioCalculator] Missing initial value for symbol AC.TO at 2021-02-15
[Nest] 845  - 09/01/2022, 9:48:22 AM   DEBUG Fetched 1 quotes from YAHOO in 1.589 seconds
[Nest] 845  - 09/01/2022, 9:48:22 AM   DEBUG ------------------------------------------------
[Nest] 845  - 09/01/2022, 9:48:22 AM   DEBUG Fetched 1 quotes in 1.591 seconds
[Nest] 845  - 09/01/2022, 9:48:22 AM   DEBUG ================================================
[Nest] 845  - 09/01/2022, 9:48:22 AM   ERROR [ExceptionsHandler] [big.js] Division by zero
Error: [big.js] Division by zero
    at Big.P.div (/ghostfolio/apps/api/node_modules/big.js/big.js:356:13)
    at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:364784)
    at Generator.next (<anonymous>)
    at fulfilled (/ghostfolio/apps/api/node_modules/tslib/tslib.js:115:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

2021-02-15 is the date of the first activity (initial purchase). I've checked the database table, all the activity entries seem fine, so not sure what is missing?

**Comment by MisterDeee** [comment]
I think this is a duplicate of #1209
