### ISSUE TITLE
[BUG] version 1.294.0 stuck on missing public.Account table

### ISSUE THREAD

**Issue by ondrejkopka** [ghostfolio/ghostfolio#2193]
**Bug Description**
ghostfolio is not possible to install, i've tried 1.294.0, 1.293.0 and 1.292.0, command `docker-compose --env-file ./.env -f docker/docker-compose.yml up` ends like this:
```
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:23 AM     LOG [RouterExplorer] Mapped {/api/info, GET} (version: 1) route +1ms
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:23 AM     LOG [RoutesResolver] SymbolController {/api/symbol} (version: 1): +1ms
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:23 AM     LOG [RouterExplorer] Mapped {/api/symbol/lookup, GET} (version: 1) route +2ms
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:23 AM     LOG [RouterExplorer] Mapped {/api/symbol/:dataSource/:symbol, GET} (version: 1) route +2ms
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:23 AM     LOG [RouterExplorer] Mapped {/api/symbol/:dataSource/:symbol/:dateString, GET} (version: 1) route +2ms
ghostfolio_1  | node_redis: Warning: Redis server does not require a password, but a password was supplied.
ghostfolio_1  | [WARN] This Redis server's `default` user does not require a password, but a password was supplied
ghostfolio_1  | [WARN] This Redis server's `default` user does not require a password, but a password was supplied
ghostfolio_1  | [WARN] This Redis server's `default` user does not require a password, but a password was supplied
postgres_1    | 2023-07-30 00:42:24.036 UTC [92] ERROR:  relation "public.Account" does not exist at character 97
postgres_1    | 2023-07-30 00:42:24.036 UTC [92] STATEMENT:  SELECT "public"."Account"."id", "public"."Account"."userId", "public"."Account"."currency" FROM "public"."Account" WHERE "public"."Account"."currency" IS NOT NULL ORDER BY "public"."Account"."currency" ASC OFFSET $1
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG [NestApplication] Nest application successfully started +359ms
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG    ________               __  ____      ___
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG   / ____/ /_  ____  _____/ /_/ __/___  / (_)___
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG  / / __/ __ \/ __ \/ ___/ __/ /_/ __ \/ / / __ \
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG / /_/ / / / / /_/ (__  ) /_/ __/ /_/ / / / /_/ /
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG \____/_/ /_/\____/____/\__/_/  \____/_/_/\____/ v1.170.0
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG Listening at http://0.0.0.0:3333
ghostfolio_1  | [Nest] 1  - 07/30/2023, 12:42:24 AM     LOG
ghostfolio_1  | (node:1) UnhandledPromiseRejectionWarning: Error: The table `public.Account` does not exist in the current database.
ghostfolio_1  |     at RequestHandler.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/index.js:49022:15)
ghostfolio_1  |     at async PrismaService._request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/index.js:49919:18)
ghostfolio_1  | (Use `node --trace-warnings ...` to show where the warning was created)
ghostfolio_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
ghostfolio_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

when i open localhost:3333, i can click on "Get stared" but button for creating new user is grey.

**To Reproduce**

1. git clone https://github.com/ghostfolio/ghostfolio.git
2. git checkout 1.294.0
3. set up `.env.` like this:
```
COMPOSE_PROJECT_NAME=ghostfolio

# CACHE
REDIS_PASSWORD=<>
REDIS_PORT=6379

# POSTGRES
POSTGRES_DB=ghostfolio-db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=<>

ACCESS_TOKEN_SALT=<>

JWT_SECRET_KEY=<>
```
4. docker-compose --env-file ./.env -f docker/docker-compose.yml up

**Expected behavior**

ghostfolio is running and i can register my user

**Environment**

- Self-hosted
- Ghostfolio Version 1.294.0
- Debian Bookworm

**Comment by ondrejkopka** [comment]
```
docker exec ghostfolio_ghostfolio_1 yarn database:migrate
docker exec ghostfolio_ghostfolio_1 yarn database:seed
```

just fixed it by running ^^
