### ISSUE TITLE
[BUG] Invalid `prisma.account.findMany()` invocation:

### ISSUE THREAD

**Issue by lsalgueiro** [ghostfolio/ghostfolio#2592]
The Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

**Bug Description**

My self-hosted instance of Ghostfolio has been raising this issue each time I try to open the Summary, Holdings (under Portfolio — the Overview is okay), Allocations and the X-ray.

**To Reproduce**

1. `git pull` repo
2. Build and run environment with docker-composer as per instructions
3. Navigate to the aforementioned pages

**Logs**

```
2023-11-04 18:27:35 [Nest] 170  - 11/04/2023, 6:27:35 PM   ERROR [ExceptionsHandler] 
2023-11-04 18:27:35 Invalid `prisma.account.findMany()` invocation:
2023-11-04 18:27:35 
2023-11-04 18:27:35 {
2023-11-04 18:27:35   cursor: undefined,
2023-11-04 18:27:35   include: {
2023-11-04 18:27:35     Platform: true,
2023-11-04 18:27:35     balances: {
2023-11-04 18:27:35       orderBy: {
2023-11-04 18:27:35         date: "desc"
2023-11-04 18:27:35       },
2023-11-04 18:27:35       take: 1
2023-11-04 18:27:35     }
2023-11-04 18:27:35   },
2023-11-04 18:27:35   orderBy: undefined,
2023-11-04 18:27:35   skip: undefined,
2023-11-04 18:27:35   take: undefined,
2023-11-04 18:27:35   where: {
2023-11-04 18:27:35     id: {
2023-11-04 18:27:35       in: [
2023-11-04 18:27:35         null
2023-11-04 18:27:35       ]
2023-11-04 18:27:35       ~~~~~~
2023-11-04 18:27:35     }
2023-11-04 18:27:35   }
2023-11-04 18:27:35 }
2023-11-04 18:27:35 
2023-11-04 18:27:35 Argument `in`: Invalid value provided. Expected ListStringFieldRefInput, provided (Null).
2023-11-04 18:27:35 PrismaClientValidationError: 
2023-11-04 18:27:35 Invalid `prisma.account.findMany()` invocation:
2023-11-04 18:27:35 
2023-11-04 18:27:35 {
2023-11-04 18:27:35   cursor: undefined,
2023-11-04 18:27:35   include: {
2023-11-04 18:27:35     Platform: true,
2023-11-04 18:27:35     balances: {
2023-11-04 18:27:35       orderBy: {
2023-11-04 18:27:35         date: "desc"
2023-11-04 18:27:35       },
2023-11-04 18:27:35       take: 1
2023-11-04 18:27:35     }
2023-11-04 18:27:35   },
2023-11-04 18:27:35   orderBy: undefined,
2023-11-04 18:27:35   skip: undefined,
2023-11-04 18:27:35   take: undefined,
2023-11-04 18:27:35   where: {
2023-11-04 18:27:35     id: {
2023-11-04 18:27:35       in: [
2023-11-04 18:27:35         null
2023-11-04 18:27:35       ]
2023-11-04 18:27:35       ~~~~~~
2023-11-04 18:27:35     }
2023-11-04 18:27:35   }
2023-11-04 18:27:35 }
2023-11-04 18:27:35 
2023-11-04 18:27:35 Argument `in`: Invalid value provided. Expected ListStringFieldRefInput, provided (Null).
2023-11-04 18:27:35     at En (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:116:5888)
2023-11-04 18:27:35     at Cn.handleRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:6516)
2023-11-04 18:27:35     at Cn.handleAndLogRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:6206)
2023-11-04 18:27:35     at Cn.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:5926)
2023-11-04 18:27:35     at async l (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:128:9968)
2023-11-04 18:27:35     at async AccountService.accounts (/ghostfolio/apps/api/main.js:1:259052)
2023-11-04 18:27:35     at async PortfolioService.getValueOfAccountsAndPlatforms (/ghostfolio/apps/api/main.js:1:339481)
2023-11-04 18:27:35     at async PortfolioService.getDetails (/ghostfolio/apps/api/main.js:1:322895)
2023-11-04 18:27:35     at async PortfolioController.getDetails (/ghostfolio/apps/api/main.js:1:342002)
2023-11-04 18:29:10 [Nest] 170  - 11/04/2023, 6:29:10 PM   ERROR [ExceptionsHandler] 
2023-11-04 18:29:10 Invalid `prisma.account.findMany()` invocation:
2023-11-04 18:29:10 
2023-11-04 18:29:10 {
2023-11-04 18:29:10   cursor: undefined,
2023-11-04 18:29:10   include: {
2023-11-04 18:29:10     Platform: true,
2023-11-04 18:29:10     balances: {
2023-11-04 18:29:10       orderBy: {
2023-11-04 18:29:10         date: "desc"
2023-11-04 18:29:10       },
2023-11-04 18:29:10       take: 1
2023-11-04 18:29:10     }
2023-11-04 18:29:10   },
2023-11-04 18:29:10   orderBy: undefined,
2023-11-04 18:29:10   skip: undefined,
2023-11-04 18:29:10   take: undefined,
2023-11-04 18:29:10   where: {
2023-11-04 18:29:10     id: {
2023-11-04 18:29:10       in: [
2023-11-04 18:29:10         null
2023-11-04 18:29:10       ]
2023-11-04 18:29:10       ~~~~~~
2023-11-04 18:29:10     }
2023-11-04 18:29:10   }
2023-11-04 18:29:10 }
2023-11-04 18:29:10 
2023-11-04 18:29:10 Argument `in`: Invalid value provided. Expected ListStringFieldRefInput, provided (Null).
2023-11-04 18:29:10 PrismaClientValidationError: 
2023-11-04 18:29:10 Invalid `prisma.account.findMany()` invocation:
2023-11-04 18:29:10 
2023-11-04 18:29:10 {
2023-11-04 18:29:10   cursor: undefined,
2023-11-04 18:29:10   include: {
2023-11-04 18:29:10     Platform: true,
2023-11-04 18:29:10     balances: {
2023-11-04 18:29:10       orderBy: {
2023-11-04 18:29:10         date: "desc"
2023-11-04 18:29:10       },
2023-11-04 18:29:10       take: 1
2023-11-04 18:29:10     }
2023-11-04 18:29:10   },
2023-11-04 18:29:10   orderBy: undefined,
2023-11-04 18:29:10   skip: undefined,
2023-11-04 18:29:10   take: undefined,
2023-11-04 18:29:10   where: {
2023-11-04 18:29:10     id: {
2023-11-04 18:29:10       in: [
2023-11-04 18:29:10         null
2023-11-04 18:29:10       ]
2023-11-04 18:29:10       ~~~~~~
2023-11-04 18:29:10     }
2023-11-04 18:29:10   }
2023-11-04 18:29:10 }
2023-11-04 18:29:10 
2023-11-04 18:29:10 Argument `in`: Invalid value provided. Expected ListStringFieldRefInput, provided (Null).
2023-11-04 18:29:10     at En (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:116:5888)
2023-11-04 18:29:10     at Cn.handleRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:6516)
2023-11-04 18:29:10     at Cn.handleAndLogRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:6206)
2023-11-04 18:29:10     at Cn.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:5926)
2023-11-04 18:29:10     at async l (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:128:9968)
2023-11-04 18:29:10     at async AccountService.accounts (/ghostfolio/apps/api/main.js:1:259052)
2023-11-04 18:29:10     at async PortfolioService.getValueOfAccountsAndPlatforms (/ghostfolio/apps/api/main.js:1:339481)
2023-11-04 18:29:10     at async PortfolioService.getDetails (/ghostfolio/apps/api/main.js:1:322895)
2023-11-04 18:29:10     at async PortfolioController.getDetails (/ghostfolio/apps/api/main.js:1:342002)
2023-11-04 18:30:03 [Nest] 170  - 11/04/2023, 6:30:03 PM   ERROR [ExceptionsHandler] 
2023-11-04 18:30:03 Invalid `prisma.account.findMany()` invocation:
2023-11-04 18:30:03 
2023-11-04 18:30:03 {
2023-11-04 18:30:03   cursor: undefined,
2023-11-04 18:30:03   include: {
2023-11-04 18:30:03     Platform: true,
2023-11-04 18:30:03     balances: {
2023-11-04 18:30:03       orderBy: {
2023-11-04 18:30:03         date: "desc"
2023-11-04 18:30:03       },
2023-11-04 18:30:03       take: 1
2023-11-04 18:30:03     }
2023-11-04 18:30:03   },
2023-11-04 18:30:03   orderBy: undefined,
2023-11-04 18:30:03   skip: undefined,
2023-11-04 18:30:03   take: undefined,
2023-11-04 18:30:03   where: {
2023-11-04 18:30:03     id: {
2023-11-04 18:30:03       in: [
2023-11-04 18:30:03         null
2023-11-04 18:30:03       ]
2023-11-04 18:30:03       ~~~~~~
2023-11-04 18:30:03     }
2023-11-04 18:30:03   }
2023-11-04 18:30:03 }
2023-11-04 18:30:03 
2023-11-04 18:30:03 Argument `in`: Invalid value provided. Expected ListStringFieldRefInput, provided (Null).
2023-11-04 18:30:03 PrismaClientValidationError: 
2023-11-04 18:30:03 Invalid `prisma.account.findMany()` invocation:
2023-11-04 18:30:03 
2023-11-04 18:30:03 {
2023-11-04 18:30:03   cursor: undefined,
2023-11-04 18:30:03   include: {
2023-11-04 18:30:03     Platform: true,
2023-11-04 18:30:03     balances: {
2023-11-04 18:30:03       orderBy: {
2023-11-04 18:30:03         date: "desc"
2023-11-04 18:30:03       },
2023-11-04 18:30:03       take: 1
2023-11-04 18:30:03     }
2023-11-04 18:30:03   },
2023-11-04 18:30:03   orderBy: undefined,
2023-11-04 18:30:03   skip: undefined,
2023-11-04 18:30:03   take: undefined,
2023-11-04 18:30:03   where: {
2023-11-04 18:30:03     id: {
2023-11-04 18:30:03       in: [
2023-11-04 18:30:03         null
2023-11-04 18:30:03       ]
2023-11-04 18:30:03       ~~~~~~
2023-11-04 18:30:03     }
2023-11-04 18:30:03   }
2023-11-04 18:30:03 }
2023-11-04 18:30:03 
2023-11-04 18:30:03 Argument `in`: Invalid value provided. Expected ListStringFieldRefInput, provided (Null).
2023-11-04 18:30:03     at En (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:116:5888)
2023-11-04 18:30:03     at Cn.handleRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:6516)
2023-11-04 18:30:03     at Cn.handleAndLogRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:6206)
2023-11-04 18:30:03     at Cn.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:123:5926)
2023-11-04 18:30:03     at async l (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:128:9968)
2023-11-04 18:30:03     at async AccountService.accounts (/ghostfolio/apps/api/main.js:1:259052)
2023-11-04 18:30:03     at async PortfolioService.getValueOfAccountsAndPlatforms (/ghostfolio/apps/api/main.js:1:339481)
2023-11-04 18:30:03     at async PortfolioService.getDetails (/ghostfolio/apps/api/main.js:1:322895)
2023-11-04 18:30:03     at async PortfolioController.getDetails (/ghostfolio/apps/api/main.js:1:342002)

```

**Environment**

- Self-hosted
- Ghostfolio Version 2.17.0, but has been going for a while
- Arc (Chromium), Safari
- MacOS Monterey 12.5

**Comment by dtslvr** [comment]
Hi @lsalgueiro

Can you reproduce this issue if you open a _New Incognito Window_ in your browser and create a new Ghostfolio user account via _Get Started_?

**Comment by lsalgueiro** [comment]
Hi, dearest Thomas,

no — everything seems operational in a new user!

**Comment by dtslvr** [comment]
> no — everything seems operational in a new user!

Thanks for checking. Please extend the steps for reproduction in your bug report. With the current instructions I'm not able to reproduce it. Thank you.

**Comment by dtslvr** [comment]
I accidentally ran into the same error during development.
