### ISSUE TITLE
Issue in PortfolioService.getPosition() on Unraid and / or server location in America

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2669]
This ticket is a follow-up for #1228. I have handled the following exception via #2667:
```
[Nest] 122  - 10/04/2023, 11:02:53 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'items')
TypeError: Cannot read properties of undefined (reading 'items')
    at PortfolioService.getPosition (/ghostfolio/apps/api/main.js:1:323878)
    at async PortfolioController.getPosition (/ghostfolio/apps/api/main.js:1:344706)
```
I have also noticed that these bug reports come from users using _Unraid_ and / or having a server located in America. Maybe the root cause [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.service.ts#L867) is related to the server's local timezone.

If you have a suggestion for improvement, please let us know.

**Comment by shiruken** [comment]
Running `ghostfolio/ghostfolio:latest` on Unraid. The `TZ` variable must be set to `""` or the application will have issues fetching historical market data as documented above and discussed in [this Unraid forum thread](https://forums.unraid.net/topic/123829-support-community-applications-ghostfolio/?do=findComment&comment=1169817). Note that Unraid automatically injects the server timezone, so this user-defined variable is overriding default Docker creation on Unraid.

**Comment by nodiaque** [comment]
Hello,

There is a know and we'll discuss issue here when using unraid, if you don't set container to timezone utc, it won't work. I just had a similar problem with another container where PostgreSQL database contained dates that were screwed because of timezone. Using tz=utc mitigate the problem but doesn't really solved it.

We've worked on the issue at the other container and the culprid was typeorm and other stuff.

See the saga here

https://github.com/Phalcode/gamevault-backend/issues/257#issuecomment-2053808077

I think you should contact falco or check the latest commit to see what change he did and how to solve this. Solving this would stopped the problem when people doesn't use utc as timezone (like everyone not in that timezone on unraid for instance)
