### ISSUE TITLE
[BUG] adding an activity impossible due to `isPremium` TypeError

### ISSUE THREAD

**Issue by slagiewka** [ghostfolio/ghostfolio#2969]
**Bug Description**

**To Reproduce**

1. Portfolio -> Activities -> Add
2. Try typing a symbol
3. Fetch for the queried symbol fails

**Expected behavior**

Typing in the symbol shows the list of possible tickers.

**Logs**

```
[Nest] 184  - 02/06/2024, 3:22:10 PM   ERROR [CoinGeckoService] RequestError: The operation to get the quotes was aborted because the request to the data provider took more than 2000ms
[Nest] 184  - 02/06/2024, 3:40:09 PM   ERROR [SymbolService] TypeError: Cannot set properties of undefined (setting 'isPremium')
[Nest] 184  - 02/06/2024, 3:40:09 PM   ERROR [ExceptionsHandler] Cannot set properties of undefined (setting 'isPremium')
TypeError: Cannot set properties of undefined (setting 'isPremium')
    at /ghostfolio/apps/api/main.js:1:209744
    at Array.map (<anonymous>)
    at DataProviderService.search (/ghostfolio/apps/api/main.js:1:209611)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SymbolService.lookup (/ghostfolio/apps/api/main.js:1:224805)
```

**Environment**

- Ghostfolio Version 2.48.0
- Self-hosted
- Experimental Features enabled or disabled : both
- Firefox 122.0
- Fedora 38

**Additional context**

Doesn't happen on previous 2.47.0. I see that there have been commits added in between that touch things related to it.

**Comment by slagiewka** [comment]
I see 2.48.1 JUST released. Will test when I get the container image :)

**Comment by slagiewka** [comment]
Never mind, 48.1 seems to fix it :wink:
