### ISSUE TITLE
[BUG] Unable to delete "Bitcoin" Asset Profile from Market Data - "Oops! Something went wrong. Please try again later."

### ISSUE THREAD

**Issue by karter16** [ghostfolio/ghostfolio#3349]
**Bug Description**

As part of trying to figure out why my Bitcoin asset profile stopped retrieving historical data I have deleted all activities associated with the Bitcoin asset profile and then tried to delete the asset profile. Doing so results in an error "Oops! Something went wrong. Please try again later." 

Checking the XHR in the browser console shows the following response

`{
    "statusCode": 500,
    "message": "Internal server error"
}`

The asset profile is not deleted

**To Reproduce**
I am unable to prove reproduction steps given I am unable to delete the asset profile and re-add it in order to test whether this is a persistent issue.

It should be noted that I can delete other asset profiles (provided they have no activities related to them) it is just the "Bitcoin" asset profile I cannot delete.

**Expected behavior**

It is possible to delete the Bitcoin asset profile.

**Screenshots**
<img width="802" alt="Screenshot 2024-05-01 at 5 56 15 PM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/ad761263-7c84-4751-9c16-ff9e053e74b5">
<img width="1124" alt="Screenshot 2024-05-01 at 5 56 53 PM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/0b253074-c84c-42a7-81a3-ecc956011659">

**Logs**

**Environment**

- Ghostfolio Version 2.77.1
- Self-hosted
- Experimental Features enabled (Note I have tried with this both enabled and disabled and the issue is present in both)
- Safari
- MacOS

**Additional context**

**Comment by karter16** [comment]
<img width="882" alt="Screenshot 2024-05-02 at 6 13 58 PM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/486c764d-d972-4310-b62b-02b7fb980f34">

**Comment by dtslvr** [comment]
Do you see anything suspicious in the server log?

**Comment by karter16** [comment]
Slightly off-topic but this probably explains why retrieving historical data is failing:

![Uploading Screenshot 2024-05-02 at 6.19.53 PM.png…]()

**Comment by karter16** [comment]
> Do you see anything suspicious in the server log?

dumb question, but what log file should I be looking in? (selfhosted, running the docker container on Debian base).

**Comment by karter16** [comment]
sorry @dtslvr I should have tagged you in above response:

dumb question, but what log file should I be looking in? (selfhosted, running the docker container on Debian base).

**Comment by karter16** [comment]
> same [here](https://github.com/ghostfolio/ghostfolio/issues/3435)

Ah that's interesting what you note in your bug re having selected it as a benchmark and then unselected before deleting - my situation is the same. I had Bitcoin marked as a benchmark

**Comment by gstr3745** [comment]
> Do you see anything suspicious in the server log?

Since I'm experiencing the same issue, I inspected the container's log:

```
[Nest] 121  - 05/28/2024, 6:21:02 AM   ERROR [ExceptionsHandler]
Invalid `prisma.symbolProfile.delete()` invocation:


Foreign key constraint failed on the field: `SymbolProfileOverrides_symbolProfileId_fkey (index)`
PrismaClientKnownRequestError:
Invalid `prisma.symbolProfile.delete()` invocation:


Foreign key constraint failed on the field: `SymbolProfileOverrides_symbolProfileId_fkey (index)`
    at In.handleRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async AdminService.deleteProfileData (/ghostfolio/apps/api/main.js:1:498924)
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/router/router-proxy.js:9:17
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/router/router-explorer.js:176:17
  
```

In another thread I read the advice to downgrate to 2.20.0 version, delete the entry and then upgrade to current.
I tried that, but it results in an unhealty container: I suppose it's a too old version.

(As far as I can remember, I never set the asset as a benchmark)

**Comment by gstr3745** [comment]
> My instance is happy and healthy 😄

You cannot imagine how that record I can't delete bothers me 😆 
But I have no experience in DB or programming, so I'm afraid of messing something up: I'm just pretending it doesn't exist (but deeply I know it does)
