### ISSUE TITLE
[BUG] Exception when disabling unconfigured Biometric Authentication

### ISSUE THREAD

**Issue by dittodhole** [ghostfolio/ghostfolio#3439]
**Bug Description**

Just wanted to try out Biometric Authentication, did not configure anything, and then wanted to disable it again.

**To Reproduce**

1. Goto user settings at `/en/account`
2. Enable "Biometric Authentication"
3. Disable "Biometric Authentication"
4. Confirm to disable.

**Expected behavior**

No failure

**Logs**

```
[Nest] 120  - 05/30/2024, 12:36:32 AM   ERROR [ExceptionsHandler] 
Invalid `prisma.authDevice.delete()` invocation:
An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
PrismaClientKnownRequestError: 
Invalid `prisma.authDevice.delete()` invocation:
An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
    at In.handleRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async AuthDeviceController.deleteAuthDevice (/ghostfolio/apps/api/main.js:1:522273)
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Environment**

- Ghostfolio Version 2.82.0
- Self-hosted
- Experimental Features enabled and disabled, tried both
- Brave 1.66.115
- Windows 11 Pro

**Comment by dtslvr** [comment]
We were unable to reproduce the issue described here with the current codebase. If you encounter this problem again, please open a new issue with detailed steps to reproduce. Thank you.
