### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by hamperfait** [ghostfolio/ghostfolio#3652]
**Bug Description**

When accessing the Overview page, it does not display how much I currently have invested. It does show the graph and the current ROI, but not the main "number". 

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/2cd160a2-aa6c-46c6-a38b-e6051bd8d9cb)

**Logs**

No useful logs in the docker logs. 

Browser logs:
```
main.a9f5126504e8e9e5.js:3  ERROR TypeError: Cannot read properties of undefined (reading 'value')
    at Qd (main.a9f5126504e8e9e5.js:3:432741)
    at b.ngOnChanges (2287.33f0b3b24f935621.js:1:13315)
    at b.Gn (main.a9f5126504e8e9e5.js:3:1278482)
    at Uf (main.a9f5126504e8e9e5.js:3:1283427)
    at Th (main.a9f5126504e8e9e5.js:3:1283583)
    at Sh (main.a9f5126504e8e9e5.js:3:1283329)
    at gu (main.a9f5126504e8e9e5.js:3:1282999)
    at mT (main.a9f5126504e8e9e5.js:3:1318596)
    at G_ (main.a9f5126504e8e9e5.js:3:1319927)
    at Xb (main.a9f5126504e8e9e5.js:3:1319749)
```

**Environment**

- Ghostfolio Version 2.102.0
- Self-hosted
- Experimental Features disabled
- Edge Browser
- Windows

**Additional context**

I saw in #1057 there is a similar error that has to do with currencies. I have mostly EUR but also some USD and crypto, my main is EUR, not sure if that could be the issue

**Comment by hamperfait** [comment]
I have modified the locale in the docker compose to see if that is the issue, set it to `UTC`, `Europe/Berlin` and `""`, did not change the error.
Running on a proxmox container, not unRaid.

**Comment by dtslvr** [comment]
Hi @hamperfait

Could you please follow our bug report template by providing detailed steps to reproduce the issue and attaching a minimal set of exported activities if possible? Thanks for your assistance.

**Comment by hamperfait** [comment]
There aren't many steps I can give... I used the docker compose image available, pulled the images and `up -d`'d the containers.
Then I added all my activities. 
I have deleted all data and added just one single activity, but the result is the same, when I go to my overview I only get the gain/loss in total and percentage, but now how much money I have invested in total. 
[ghostfolio-export-202408101220.json](https://github.com/user-attachments/files/16579149/ghostfolio-export-202408101220.json)
I attached a copy of the export with a subset of the investments, hope it helps

**Comment by dw-0** [comment]
I wasn't able to reproduce the reported issue. I used the provided json to add some similar activities to my local development account (sadly there is no json import) but with the current development state of the application, no issues can be seen on the overview page.
![image](https://github.com/user-attachments/assets/59dca14b-8187-4287-bb10-0b3d20279351)

@hamperfait is this issue still present with the latest ghostfolio version?

**Comment by hamperfait** [comment]
Hi,

Unfortunately yes, it is still not displaying the total amount in EUR using v 2.119.0. It works fine otherwise, I have tried re-importing the data, removing and adding it again, still got the same issue. Only thing I know is when I load the dashboard I get the error 
```
main.de7c0ab998104302.js:3  ERROR TypeError: Cannot read properties of undefined (reading 'value')
    at Sa (main.de7c0ab998104302.js:3:433021)
    at b.ngOnChanges (2287.b79a0f0d851dfc9a.js:1:13946)
    at b.mi (main.de7c0ab998104302.js:3:1157523)
    at vu (main.de7c0ab998104302.js:3:1162471)
    at cd (main.de7c0ab998104302.js:3:1162627)
    at Ul (main.de7c0ab998104302.js:3:1162373)
    at Xl (main.de7c0ab998104302.js:3:1162043)
    at TI (main.de7c0ab998104302.js:3:1201558)
    at XA (main.de7c0ab998104302.js:3:1202889)
    at Ov (main.de7c0ab998104302.js:3:1202711)
```

**Comment by Kaysera** [comment]
Sorry to bump the issue but I find the same problem both in my self-hosted instance and in the Live Demo. I am thinking that it might be something related to the locale as well, because it happens to me in Brave Browser and Edge, so maybe it is reading something from the browser that does not match what it expects?
