### ISSUE TITLE
[BUG] Crash due to cron 

### ISSUE THREAD

**Issue by SvbZ3r0** [ghostfolio/ghostfolio#3692]
**Bug Description**

Docker dontainer crashes every day

**Logs**
```
/ghostfolio/apps/api/node_modules/cron/lib/time.js:272
                                        throw new Error(
                                        ^

Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.
                                                        Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
                                                        Time Zone: "" - Cron String: 0 0 * * * * - UTC offset: 330
                                                        - current Date: 2024-08-23T05:36:36.177+05:30
    at CT._getNextDateFrom (/ghostfolio/apps/api/node_modules/cron/lib/time.js:272:12)
    at CT.sendAt (/ghostfolio/apps/api/node_modules/cron/lib/time.js:185:17)
    at CT.getTimeout (/ghostfolio/apps/api/node_modules/cron/lib/time.js:202:29)
    at CJ.start (/ghostfolio/apps/api/node_modules/cron/lib/job.js:119:31)
    at Timeout.callbackWrapper [as _onTimeout] (/ghostfolio/apps/api/node_modules/cron/lib/job.js:172:11)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
```
The mentioned upstream issue (https://github.com/kelektiv/node-cron/issues/467) seems to have been fixed in a later version: https://github.com/kelektiv/node-cron/commit/c685c63a6d7fa86d6c8afca29b536b9da24e824b

**Environment**

- Ghostfolio Version 2.104.1 - 2024-08-17
- Self-hosted
- Experimental Features disabled
- Browser - Chrome
- OS - Unraid
- Docker container - https://hub.docker.com/r/ghostfolio/ghostfolio

**Comment by intcreator** [comment]
good news, this package is now depending on a later version of cron that fixed the bug, so this issue can be closed

**Comment by SvbZ3r0** [comment]
I haven't faced this issue in quite a while. Don't remember from which version. Closing since it is resolved.
