### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VibeNL** [ghostfolio/ghostfolio#3755]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

Lots of errors in the logs:
Nest] 103  - 09/12/2024, 5:31:13 PM   ERROR [ExceptionsHandler] job stalled more than allowable limit
Error: job stalled more than allowable limit
    at Job.finished (/ghostfolio/apps/api/node_modules/bull/lib/job.js:494:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TWRPortfolioCalculator.initialize (/ghostfolio/apps/api/main.js:1:428569)
    at async TWRPortfolioCalculator.getSnapshot (/ghostfolio/apps/api/main.js:1:425138)
    at async PortfolioService.getDetails (/ghostfolio/apps/api/main.js:1:485385)
    at async Promise.all (index 1)
    at async PortfolioService.getAccounts (/ghostfolio/apps/api/main.js:1:482711)
    at async PortfolioService.getAccountsWithAggregations (/ghostfolio/apps/api/main.js:1:483404)

**To Reproduce**

Have it running.

**Expected behavior**

A working application

**Screenshots**

**Logs**

See above

**Environment**

- Ghostfolio Version 2.107.0
-  Self-hosted
- Experimental Features disabled
- Browser
- OS

**Additional context**

**Comment by flowcool** [comment]
Same here and have to reboot container and flush data :(

**Comment by flowcool** [comment]
@dtslvr : Does it ring a bell, any plan for a fix ?

**Comment by ceroma** [comment]
Just in case it helps someone - I currently have the following locally to get around this issue:
```
BullModule.registerQueue({
  name: PORTFOLIO_SNAPSHOT_QUEUE,
  settings: {
    lockDuration: 600000,
    stalledInterval: 0
  }
}),
```
in `apps/api/src/services/queues/portfolio-snapshot/portfolio-snapshot.module.ts`

I'm not too familiar with `@nestjs/bull` but seems like the default `lockDuration` is 30s, so if a job takes more than that it's marked as stalled. But without the changes above sometimes I'd get this error and sometimes I wouldn't, even though my snapshot takes way longer than 30s, so I'm not confident that just raising `lockDuration` is the right fix. Based on a quick read of the docs, it seems like the best thing to do would be to run the computation on a [separate process](https://docs.nestjs.com/techniques/queues#separate-processes-1) but it appears that doing so isn't a trivial task. Maybe a combination of `lockDuration` and the other `stalled` options, possibly exposed via env vars, might be enough?

**Comment by reedhaffner** [comment]
Same here, same error.

**Comment by longstone** [comment]
I've the same error with ghostfolio:2.127.0, ghostfolio is not accessible. Error {"statusCode":500,"message":"Internal server error"}. Even after rebooting and flushing data.

**Comment by dtslvr** [comment]
> I've the same error with ghostfolio:2.127.0, ghostfolio is not accessible. Error {"statusCode":500,"message":"Internal server error"}. Even after rebooting and flushing data.

Please upgrade to the latest version ([2.128.0](https://github.com/ghostfolio/ghostfolio/releases/tag/2.128.0)) and flush the cache.

**Comment by VibeNL** [comment]
It did the trick for a while. However is seems te be happening again and again. Most likely due to the increase of data.

**Comment by KhoaNguy3n** [comment]
Any updates on this please?

I did the followings and the issue still occurred:

- Update to the latest version
- Flush the cache
