### ISSUE TITLE
[BUG] Failures in prisma.marketData.findMany

### ISSUE THREAD

**Issue by ms32035** [ghostfolio/ghostfolio#3821]
**Bug Description**

Following the upgrade to 2.109.0, I think related to the concurrent processing, I'm now getting a ton of
```
Server has closed the connection.
Error: PrismaClientKnownRequestError: 
Invalid `prisma.marketData.findMany()` invocation:


Server has closed the connection.
    at Job.finished (/ghostfolio/apps/api/node_modules/bull/lib/job.js:494:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TWRPortfolioCalculator.initialize (/ghostfolio/apps/api/main.js:1:431935)
    at async TWRPortfolioCalculator.getSnapshot (/ghostfolio/apps/api/main.js:1:428504)
    at async PortfolioService.getPerformance (/ghostfolio/apps/api/main.js:1:498079)
    at async PortfolioController.getPerformanceV2 (/ghostfolio/apps/api/main.js:1:513620)
[Nest] 119  - 09/25/2024, 9:27:00 PM   ERROR [ExceptionsHandler] PrismaClientKnownRequestError: 
```
And the app is generally broken. Nothing interesting in the logs on the Postgres side, only `TC [66] LOG:  could not receive data from client: Connection reset by peer`

The issue does not seem to be related to #2653

**To Reproduce**

???

**Expected behavior**

Correctly executed queries

**Screenshots**

![Screenshot from 2024-09-25 22-34-01](https://github.com/user-attachments/assets/ddf5565e-cc2d-4ba2-8259-1595c8b5d9ba)

**Logs**

See above

**Environment**

- Ghostfolio Version 2.111.0
- Self-hosted
- Edge
- docker image `ghostfolio/ghostfolio:latest`
- Postgres 15.7

**Additional context**

**Comment by ms32035** [comment]
Might be something with the caching layer, as flushing the cache seems to have resolved the issue. @dtslvr please advise as looks like more people are facing this and close the issue

**Comment by dtslvr** [comment]
I have created a new issue (https://github.com/ghostfolio/ghostfolio/issues/4535) with some more context.
