### ISSUE TITLE
[BUG] big.js error while fetching historical currency data

### ISSUE THREAD

**Issue by b-reich** [ghostfolio/ghostfolio#3868]
**Bug Description**
Hi, I have a fresh install of ghostfolio. And I try to setup my portfolio. When setting up, I noticed errors with big.js

**To Reproduce**

1. Fresh Install
2. Add EUR and GBP as currency
3. Lets fetch it historical data

**Expected behavior**

Get all historical data for the newly added currency

**Screenshots**
![image](https://github.com/user-attachments/assets/bf8d696b-8c69-4ee3-9a8b-e40ac01b4077)

**Logs**

```
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:36 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDEUR (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:37 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been completed for USDEUR (YAHOO) at 2024-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:40 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDGBP (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:40 AM   ERROR [DataProviderService] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:40 AM   ERROR [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:45 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDGBp (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:45 AM   ERROR [DataProviderService] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:45 AM   ERROR [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:49 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDUSX (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:50 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been completed for USDUSX (YAHOO) at 2024-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:11:40 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDGBP (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:11:41 AM   ERROR [DataProviderService] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:11:41 AM   ERROR [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:11:45 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDGBp (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:11:45 AM   ERROR [DataProviderService] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:11:45 AM   ERROR [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:12 AM     LOG [PortfolioChangedListener] Portfolio of user '430135c6-275b-48d4-82d7-96a6cdf43ee1' has changed
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:36 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDEUR (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:37 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been completed for USDEUR (YAHOO) at 2024-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:40 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDGBP (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:40 AM   ERROR [DataProviderService] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:40 AM   ERROR [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:45 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDGBp (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:45 AM   ERROR [DataProviderService] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:45 AM   ERROR [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Error: [big.js] Invalid number
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:49 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been started for USDUSX (YAHOO) at 2014-10-04
ghostfolio-1  | [Nest] 178  - 10/04/2024, 9:10:50 AM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been completed for USDUSX (YAHOO) at 2024-10-04
```

```
[ "Error: Error: [big.js] Invalid number\n at DataGatheringProcessor.gatherHistoricalMarketData (/ghostfolio/apps/api/main.js:1:373025)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)", "Error: Error: [big.js] Invalid number\n at DataGatheringProcessor.gatherHistoricalMarketData (/ghostfolio/apps/api/main.js:1:373025)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)", "Error: Error: [big.js] Invalid number\n at DataGatheringProcessor.gatherHistoricalMarketData (/ghostfolio/apps/api/main.js:1:373025)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)" ]
```
**Environment**

- Ghostfolio Version 2.112.0 
- Self-hosted
- Experimental Features disabled
- Firefox
- Docker/Debian

**Additional context**

**Comment by dtslvr** [comment]
@dandevaud is this related to your fix (https://github.com/ghostfolio/ghostfolio/pull/3858)?

**Comment by dandevaud** [comment]
Yes, I had exactly the same problem with USDGBP.
