### ISSUE TITLE
[BUG] 2.121.0 breaks due to missing apiKey

### ISSUE THREAD

**Issue by dittodhole** [ghostfolio/ghostfolio#4012]
**Bug Description**

Updated to 2.121.0, coming from 2.120.0, gives me an exception.

**To Reproduce**

See above

**Expected behavior**

Update works

**Logs**

> ghostfolio-1  | [Nest] 134  - 11/02/2024, 4:42:41 PM   ERROR [ExceptionHandler] Neither apiKey nor config.authenticator provided
> ghostfolio-1  | Error: Neither apiKey nor config.authenticator provided
> ghostfolio-1  |     at Stripe._setAuthenticator (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:166:23)
> ghostfolio-1  |     at new Stripe (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:102:14)
> ghostfolio-1  |     at new SubscriptionService (/ghostfolio/apps/api/main.js:1:76274)
> ghostfolio-1  |     at Injector.instantiateClass (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:365:19)
> ghostfolio-1  |     at callback (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:65:45)
> ghostfolio-1  |     at async Injector.resolveConstructorParams (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:144:24)
> ghostfolio-1  |     at async Injector.loadInstance (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:70:13)
> ghostfolio-1  |     at async Injector.loadProvider (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:97:9)
> ghostfolio-1  |     at async /ghostfolio/apps/api/node_modules/@nestjs/core/injector/instance-loader.js:56:13
> ghostfolio-1  |     at async Promise.all (index 3)
> ghostfolio-1 exited with code 0

**Environment**

- Ghostfolio Version 2.121.0
- Self-hosted
- Experimental Features enabled
- Brave v1.71.121
- Arch

**Comment by dragosde** [comment]
Same here:

```
[Nest] 98  - 11/02/2024, 4:09:24 PM     LOG [InstanceLoader] MarketDataModule dependencies initialized +1ms
[Nest] 98  - 11/02/2024, 4:09:24 PM   ERROR [ExceptionHandler] Neither apiKey nor config.authenticator provided
Error: Neither apiKey nor config.authenticator provided
    at Stripe._setAuthenticator (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:166:23)
    at new Stripe (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:102:14)
    at new SubscriptionService (/ghostfolio/apps/api/main.js:1:76274)
    at Injector.instantiateClass (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:65:45)
    at async Injector.resolveConstructorParams (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
```

**Comment by MosizZ** [comment]
Same here - Logs:
[Nest] 107  - 11/02/2024, 5:18:38 PM   ERROR [ExceptionHandler] Neither apiKey nor config.authenticator provided
Error: Neither apiKey nor config.authenticator provided
    at Stripe._setAuthenticator (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:166:23)
    at new Stripe (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:102:14)
    at new SubscriptionService (/ghostfolio/apps/api/main.js:1:76274)
    at Injector.instantiateClass (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:65:45)
    at async Injector.resolveConstructorParams (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
Running database migrations
+ echo Running database migrations
+ npx prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "ghostfolio-db", schema "public" at "ghostfolio-db:5432"
91 migrations found in prisma/migrations
No pending migrations to apply.
+ echo Seeding the database
Seeding the database
+ npx prisma db seed
Running seed command `node prisma/seed.js` ...



Container lost Docker Network a few second safter Start.

**Comment by sam-memko** [comment]
Same issue here.

`Error: Neither apiKey nor config.authenticator provided
    at Stripe._setAuthenticator (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:166:23)
    at new Stripe (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:102:14)
    at new SubscriptionService (/ghostfolio/apps/api/main.js:1:76274)
    at Injector.instantiateClass (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:65:45)
    at async Injector.resolveConstructorParams (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)`

Ghostfolio Version 2.121.0
Self-hosted
Experimental Features NOIT enabled
