### ISSUE TITLE
[BUG] NEither apiKEy nor config.authenticator provided

### ISSUE THREAD

**Issue by Se7enair** [ghostfolio/ghostfolio#4018]
**Bug Description**

Just updated to the newest version and got this error
```ghostfolio   | [Nest] 126  - 11/03/2024, 12:40:44 PM   ERROR [ExceptionHandler] Neither apiKey nor config.authenticator provided
ghostfolio   | Error: Neither apiKey nor config.authenticator provided
ghostfolio   |     at Stripe._setAuthenticator (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:166:23)
ghostfolio   |     at new Stripe (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:102:14)
ghostfolio   |     at new SubscriptionService (/ghostfolio/apps/api/main.js:1:76274)
ghostfolio   |     at Injector.instantiateClass (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:365:19)
ghostfolio   |     at callback (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:65:45)
ghostfolio   |     at async Injector.resolveConstructorParams (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:144:24)
ghostfolio   |     at async Injector.loadInstance (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:70:13)
ghostfolio   |     at async Injector.loadProvider (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:97:9)
ghostfolio   |     at async /ghostfolio/apps/api/node_modules/@nestjs/core/injector/instance-loader.js:56:13
ghostfolio   |     at async Promise.all (index 3)
ghostfolio exited with code 1
```

**To Reproduce**

1. Update container via docker compose pull
2. start container via docker compose up -d

docker-compose.yml
```name: ghostfolio
services:
  ghostfolio:
    image: docker.io/ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    init: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 3333:3333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:3333/api/v1/health
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: docker.io/library/postgres:15
    container_name: gf-postgres
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: docker.io/library/redis:alpine
    container_name: gf-redis
    user: 999:1000
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    command:
      - redis-server
      - --requirepass
      - $REDIS_PASSWORD
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli --pass "$REDIS_PASSWORD" ping | grep PONG
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres: null
```

**Expected behavior**

Start normal

**Screenshots**

**Logs**

See above

**Environment**

- Ghostfolio Version 2.121.0
- unfortunately I dont know the last working version
- self hosted
- no experimental features

**Additional context**

**Comment by Se7enair** [comment]
2.121.1 fixed that
