### ISSUE TITLE
[BUG] Building Storybook fails

### ISSUE THREAD

**Issue by carlos-ds** [ghostfolio/ghostfolio#4156]
**Bug Description**

Trying to build Storybook with the corresponding script results in a bunch of errors and a broken build

**To Reproduce**

1. `npm install` 
2. `npm run build:storybook`

Output:

```
npm run build:storybook

> ghostfolio@2.131.0 build:storybook
> nx run ui:build-storybook

Nx is configured to use the legacy cache. This cache will be removed in Nx 21. Read more at https://nx.dev/deprecated/legacy-cache.

> nx run ui:build-storybook

info => Cleaning outputDir: dist/storybook/ui
info => Loading presets
info => Building manager..
info => Manager built (267 ms)
info => Building preview..
info Addon-docs: using MDX3
info => Using implicit CSS loaders
info => Using angular browser target options from "ui:build-storybook"
info => Using angular project with "tsConfig:/Users/karel.desmet/projects/ghostfolio/libs/ui/.storybook/tsconfig.json"
    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browserslist configuration. For more information, see https://angular.dev/tools/cli/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
info => Using default Webpack5 setup
WARN export 'FireCalculatorComponent' (imported as 'FireCalculatorComponent') was not found in './fire-calculator.component' (possible exports: GfFireCalculatorComponent)
WARN export 'FireCalculatorComponent' (imported as 'FireCalculatorComponent') was not found in './fire-calculator.component' (possible exports: GfFireCalculatorComponent)
WARN export 'GfValueModule' (imported as 'GfValueModule') was not found in '../value' (possible exports: GfValueComponent)
WARN export 'LineChartComponent' (imported as 'LineChartComponent') was not found in './line-chart.component' (possible exports: GfLineChartComponent)
WARN export 'LineChartComponent' (imported as 'LineChartComponent') was not found in './line-chart.component' (possible exports: GfLineChartComponent)
WARN export 'LogoComponent' (imported as 'LogoComponent') was not found in './logo.component' (possible exports: GfLogoComponent)
WARN export 'NoTransactionsInfoComponent' (imported as 'NoTransactionsInfoComponent') was not found in './no-transactions-info.component' (possible exports: GfNoTransactionsInfoComponent)
WARN export 'GfLogoModule' (imported as 'GfLogoModule') was not found in '@ghostfolio/ui/logo' (possible exports: GfLogoComponent)
WARN export 'PortfolioProportionChartComponent' (imported as 'PortfolioProportionChartComponent') was not found in './portfolio-proportion-chart.component' (possible exports: GfPortfolioProportionChartComponent)
WARN export 'PortfolioProportionChartComponent' (imported as 'PortfolioProportionChartComponent') was not found in './portfolio-proportion-chart.component' (possible exports: GfPortfolioProportionChartComponent)
WARN export 'PremiumIndicatorComponent' (imported as 'PremiumIndicatorComponent') was not found in './premium-indicator.component' (possible exports: GfPremiumIndicatorComponent)
WARN export 'TrendIndicatorComponent' (imported as 'TrendIndicatorComponent') was not found in './trend-indicator.component' (possible exports: GfTrendIndicatorComponent)
WARN export 'ValueComponent' (imported as 'ValueComponent') was not found in './value.component' (possible exports: GfValueComponent)
libs/ui/src/lib/fire-calculator/fire-calculator.component.stories.ts:10:16 - error TS2724: '"@storybook/angular"' has no exported member named 'Story'. Did you mean 'IStory'?

10 import { Meta, Story, moduleMetadata } from '@storybook/angular';
                  ~~~~~

libs/ui/src/lib/fire-calculator/fire-calculator.component.stories.ts:13:10 - error TS2305: Module '"../value"' has no exported member 'GfValueModule'.

13 import { GfValueModule } from '../value';
            ~~~~~~~~~~~~~

libs/ui/src/lib/fire-calculator/fire-calculator.component.stories.ts:14:10 - error TS2724: '"./fire-calculator.component"' has no exported member named 'FireCalculatorComponent'. Did you mean 'GfFireCalculatorComponent'?

14 import { FireCalculatorComponent } from './fire-calculator.component';
            ~~~~~~~~~~~~~~~~~~~~~~~

  libs/ui/src/lib/fire-calculator/fire-calculator.component.ts:77:14
    77 export class GfFireCalculatorComponent implements OnChanges, OnDestroy {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~
    'GfFireCalculatorComponent' is declared here.

libs/ui/src/lib/line-chart/line-chart.component.stories.ts:2:16 - error TS2724: '"@storybook/angular"' has no exported member named 'Story'. Did you mean 'IStory'?

2 import { Meta, Story, moduleMetadata } from '@storybook/angular';
                 ~~~~~

libs/ui/src/lib/line-chart/line-chart.component.stories.ts:5:10 - error TS2724: '"./line-chart.component"' has no exported member named 'LineChartComponent'. Did you mean 'GfLineChartComponent'?

5 import { LineChartComponent } from './line-chart.component';
           ~~~~~~~~~~~~~~~~~~

  libs/ui/src/lib/line-chart/line-chart.component.ts:48:14
    48 export class GfLineChartComponent
                    ~~~~~~~~~~~~~~~~~~~~
    'GfLineChartComponent' is declared here.

libs/ui/src/lib/logo/logo.component.stories.ts:1:16 - error TS2724: '"@storybook/angular"' has no exported member named 'Story'. Did you mean 'IStory'?

1 import { Meta, Story, moduleMetadata } from '@storybook/angular';
                 ~~~~~

libs/ui/src/lib/logo/logo.component.stories.ts:3:10 - error TS2724: '"./logo.component"' has no exported member named 'LogoComponent'. Did you mean 'GfLogoComponent'?

3 import { LogoComponent } from './logo.component';
           ~~~~~~~~~~~~~

  libs/ui/src/lib/logo/logo.component.ts:18:14
    18 export class GfLogoComponent {
                    ~~~~~~~~~~~~~~~
    'GfLogoComponent' is declared here.

libs/ui/src/lib/no-transactions-info/no-transactions-info.component.stories.ts:1:10 - error TS2305: Module '"@ghostfolio/ui/logo"' has no exported member 'GfLogoModule'.

1 import { GfLogoModule } from '@ghostfolio/ui/logo';
           ~~~~~~~~~~~~

libs/ui/src/lib/no-transactions-info/no-transactions-info.component.stories.ts:4:16 - error TS2724: '"@storybook/angular"' has no exported member named 'Story'. Did you mean 'IStory'?

4 import { Meta, Story, moduleMetadata } from '@storybook/angular';
                 ~~~~~

libs/ui/src/lib/no-transactions-info/no-transactions-info.component.stories.ts:6:10 - error TS2724: '"./no-transactions-info.component"' has no exported member named 'NoTransactionsInfoComponent'. Did you mean 'GfNoTransactionsInfoComponent'?

6 import { NoTransactionsInfoComponent } from './no-transactions-info.component';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  libs/ui/src/lib/no-transactions-info/no-transactions-info.component.ts:21:14
    21 export class GfNoTransactionsInfoComponent {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'GfNoTransactionsInfoComponent' is declared here.

libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.stories.ts:3:16 - error TS2724: '"@storybook/angular"' has no exported member named 'Story'. Did you mean 'IStory'?

3 import { Meta, Story, moduleMetadata } from '@storybook/angular';
                 ~~~~~

libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.stories.ts:6:10 - error TS2724: '"./portfolio-proportion-chart.component"' has no exported member named 'PortfolioProportionChartComponent'. Did you mean 'GfPortfolioProportionChartComponent'?

6 import { PortfolioProportionChartComponent } from './portfolio-proportion-chart.component';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts:57:14
    57 export class GfPortfolioProportionChartComponent
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'GfPortfolioProportionChartComponent' is declared here.

libs/ui/src/lib/premium-indicator/premium-indicator.component.stories.ts:3:16 - error TS2724: '"@storybook/angular"' has no exported member named 'Story'. Did you mean 'IStory'?

3 import { Meta, Story, moduleMetadata } from '@storybook/angular';
                 ~~~~~

libs/ui/src/lib/premium-indicator/premium-indicator.component.stories.ts:5:10 - error TS2724: '"./premium-indicator.component"' has no exported member named 'PremiumIndicatorComponent'. Did you mean 'GfPremiumIndicatorComponent'?

5 import { PremiumIndicatorComponent } from './premium-indicator.component';
           ~~~~~~~~~~~~~~~~~~~~~~~~~

  libs/ui/src/lib/premium-indicator/premium-indicator.component.ts:18:14
    18 export class GfPremiumIndicatorComponent {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'GfPremiumIndicatorComponent' is declared here.

libs/ui/src/lib/trend-indicator/trend-indicator.component.stories.ts:1:16 - error TS2724: '"@storybook/angular"' has no exported member named 'Story'. Did you mean 'IStory'?

1 import { Meta, Story, moduleMetadata } from '@storybook/angular';
                 ~~~~~

libs/ui/src/lib/trend-indicator/trend-indicator.component.stories.ts:4:10 - error TS2724: '"./trend-indicator.component"' has no exported member named 'TrendIndicatorComponent'. Did you mean 'GfTrendIndicatorComponent'?

4 import { TrendIndicatorComponent } from './trend-indicator.component';
           ~~~~~~~~~~~~~~~~~~~~~~~

  libs/ui/src/lib/trend-indicator/trend-indicator.component.ts:20:14
    20 export class GfTrendIndicatorComponent {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~
    'GfTrendIndicatorComponent' is declared here.

libs/ui/src/lib/value/value.component.stories.ts:1:16 - error TS2724: '"@storybook/angular"' has no exported member named 'Story'. Did you mean 'IStory'?

1 import { Meta, Story, moduleMetadata } from '@storybook/angular';
                 ~~~~~

libs/ui/src/lib/value/value.component.stories.ts:4:10 - error TS2724: '"./value.component"' has no exported member named 'ValueComponent'. Did you mean 'GfValueComponent'?

4 import { ValueComponent } from './value.component';
           ~~~~~~~~~~~~~~

  libs/ui/src/lib/value/value.component.ts:22:14
    22 export class GfValueComponent implements OnChanges {
                    ~~~~~~~~~~~~~~~~
    'GfValueComponent' is declared here.

=> Failed to build the preview
SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when compiling your code with Webpack.
Run Storybook with --debug-webpack for more information.
    at ./node_modules/@storybook/builder-webpack5/dist/index.js:1:25143
    at ./node_modules/webpack/lib/HookWebpackError.js:67:2
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (./node_modules/webpack/lib/Cache.js:154:23)
    at ./node_modules/webpack/lib/Compiler.js:1379:15
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (./node_modules/webpack/lib/Compiler.js:1372:23)
    at ./node_modules/@storybook/builder-webpack5/dist/index.js:1:25128
    at finalCallback (./node_modules/webpack/lib/Compiler.js:500:32)
    at ./node_modules/webpack/lib/Compiler.js:524:13
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/tapable/lib/Hook.js:18:14)
    at onCompiled (./node_modules/webpack/lib/Compiler.js:522:21)
    at ./node_modules/webpack/lib/Compiler.js:1350:17
    at eval (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 NX   Broken build, fix the error above.

You may need to refresh the browser.


——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target build-storybook for project ui (27s)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]
```

**Expected behavior**

A successful build and output message.

**Environment**

- Ghostfolio v2.131.0
- Cloud
- Experimental Features disabled
- MacOS v14.6.1
- Node v20.16.0

**Comment by carlos-ds** [comment]
@dtslvr can you assign me to this issue? Thanks!
